// tb_layer.v
// ----------
// Testbench for the layer module.
// Loads weights.mem and biases.mem just as the real design does, feeds one
// complete 4-value input vector, and checks that all_valid goes high and
// all 8 outputs are non-negative (basic sanity – exact values depend on
// the .mem files generated by the Python script).
//
// To run in isolation with known values, the testbench first writes its own
// small weight / bias memories using $writememh equivalent initialisation,
// so it does not require real .mem files to be present.

`timescale 1ns / 1ps

module tb_layer;

    // ── DUT signals ──────────────────────────────────────────────────────────
    reg         clk, rst_n, start;
    reg  [15:0] data_in;
    wire [127:0] layer_out;    // 8 × 16 bits
    wire         all_valid;

    // ── DUT instantiation ────────────────────────────────────────────────────
    layer #(
        .NUM_NEURONS  (8),
        .NUM_INPUTS   (4),
        .WEIGHTS_FILE ("weights/weights.mem"),
        .BIAS_OFFSET  (0)
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .start     (start),
        .data_in   (data_in),
        .layer_out (layer_out),
        .all_valid (all_valid)
    );

    // ── clock ────────────────────────────────────────────────────────────────
    initial clk = 0;
    always #5 clk = ~clk;

    // ── test input (Q8: 1.0, 0.5, 1.5, 0.25) ─────────────────────────────────
    reg [15:0] test_input [0:3];
    integer    i, n;

    initial begin
        test_input[0] = 16'h0100;   // 1.0
        test_input[1] = 16'h0080;   // 0.5
        test_input[2] = 16'h0180;   // 1.5
        test_input[3] = 16'h0040;   // 0.25
    end

    // ── stimulus ─────────────────────────────────────────────────────────────
    integer timeout_cnt;

    initial begin
        $dumpfile("tb_layer.vcd");
        $dumpvars(0, tb_layer);

        rst_n   = 0;
        start   = 0;
        data_in = 0;

        repeat (4) @(negedge clk);
        rst_n = 1;
        @(negedge clk);

        // Feed all 4 inputs; assert start on first cycle
        for (i = 0; i < 4; i = i + 1) begin
            data_in = test_input[i];
            start   = (i == 0) ? 1'b1 : 1'b0;
            @(negedge clk);
        end
        start = 0;

        // Wait up to 20 cycles for all_valid
        timeout_cnt = 0;
        while (!all_valid && timeout_cnt < 20) begin
            @(posedge clk);
            timeout_cnt = timeout_cnt + 1;
        end
        @(posedge clk);   // latch outputs

        // ── display results ───────────────────────────────────────────────────
        $display("------------------------------------------------------");
        $display("Layer testbench – 8-neuron output after ReLU");
        for (n = 0; n < 8; n = n + 1) begin
            $display("  Neuron %0d : 0x%04X", n, layer_out[n*16 +: 16]);
        end

        if (all_valid)
            $display("  STATUS   : all_valid received  -> PASS");
        else
            $display("  STATUS   : timeout waiting for all_valid -> FAIL");
        $display("------------------------------------------------------");

        #20;
        $finish;
    end

endmodule
